version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: test
          command: ./gradlew test
      - run:
          name: jacoco
          command: ./gradlew jacocoTestReport
      - save_cache:
          paths:
            - ~/build/reports/jacoco/test
          key: jacoco-{{ checksum "~/build/reports/jacoco/test/jacocoTestReport.xml" }}
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
general:
  artifacts:
    - "build/reports/jacoco"